In [26]:
# 3 for loop method
def mul(A,B):
  C = []
  q = 0
  n = len(A)
  for k in range(n):
    for i in range(n):
      q = 0
      for j in range(n):
          q += A[k][j] * B[j][i]
      C[k][i] = q
  return C


# divide and conquer method
import numpy as np
def split(m):
  n = len(m)
  return m[:n//2, :n//2],m[:n//2, n//2:], m[n//2:, :n//2],  m[n//2:, n//2:]

def alg(a,b,n):
  a11,a12,a21,a22 = split(a)
  b11,b12,b21,b22 = split(b)
  if n <= 2:
    c11 = a11*b11+a12*b21
    c12 = a11*b12+a12*b22
    c21 = a21*b11 + a22*b21
    c22 = a21*b12 + a22*b22
    top = np.hstack((c11,c12))
    bottom = np.hstack((c21,c22))
    return np.vstack((top,bottom))

  c11 = alg(a11,b11,len(a11)) + alg(a12,b21,len(a12))
  c12 = alg(a11,b12,len(a11)) + alg(a12,b22,len(a12))
  c21 = alg(a21,b11,len(a21)) + alg(a22,b21,len(a22))
  c22 = alg(a21,b12,len(a21)) + alg(a22,b22,len(a22))
  top = np.hstack((c11,c12))
  bottom = np.hstack((c21,c22))
  return np.vstack((top,bottom))

a = np.array([[2,3,4,5],[1,2,3,4],[4,5,6,7],[5,4,6,7]])
b = np.array([[1,2,3,4],[2,3,4,5],[6,5,4,3],[1,2,22,54]])
n = len(a)

print(alg(a,b,n))


[[ 37  43 144 305]
 [ 27  31 111 239]
 [ 57  67 210 437]
 [ 56  66 209 436]]
